### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by d00nn1** [scottsweb/instant-search-suggest#5]
sory my english is not so good i am whery neu in this site i download it and lok whery fast and whery good but i have a problem with the Magic Mode thets dosent work so good thets meack problems to my site can sombody send me a neu code when somwon tap on  product to redirect to the post page  
thex

**Comment by scottsweb** [comment]
Sounds like you may have a JavaScript issue on your site, without a link to your site it will not be possible to work out what has gone wrong.
